### ISSUE TITLE
click % button crash

### ISSUE THREAD

**Issue by sinyo-matu** [KaiHotz/React-Mac-Calculator#1]
If I click % button from start, website would crash. error output is below
<img width="1048" alt="スクリーンショット 2021-03-14 17 05 49" src="https://user-images.githubusercontent.com/3389913/111061610-9b22e800-84e7-11eb-84fc-052d5883dc22.png">

**Comment by KaiHotz** [comment]
@sinyo-matu Hi i finally found some time to rewrite this lib into typescript, and publish the new version, so in case you still have some usage for it, it is now updated

**Comment by sinyo-matu** [comment]
> @sinyo-matu Hi i finally found some time to rewrite this lib into typescript, and publish the new version, so in case you still have some usage for it, it is now updated

Actually I am still using it in one of my personal tools. And I like it.So happy to see a new version published!Thank you so much!
